name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      ASSETS_COMMIT: ${{ secrets.ASSETS_COMMIT }}
      ASSETS_TOKEN: ${{ secrets.ASSETS_TOKEN }}
